### ISSUE TITLE
Failed to release v0.7.0

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter-resource-usage#165]
## Description

https://github.com/davidbrochart/jupyter_releaser/actions/runs/3766284063/jobs/6402622540
```
creating virtual environment...
installing twine...
Checking dist/jupyter_resource_usage-0.7.0-py3-none-any.whl: PASSED
creating virtual environment...
installing validate-pyproject from spec 'validate-pyproject[all]'...
Error:  `data` must not contain {'license'} properties
Invalid file: pyproject.toml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 122, in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 470, in check_python
    python.check_dist(
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/python.py", line 46, in check_dist
    util.run(cmd.format(**locals()))
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 91, in run
    raise e
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 83, in run
    process = tee(cmd, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/tee.py", line 159, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'pipx run 'validate-pyproject[all]' pyproject.toml' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/actions/populate_release.py", line 40, in <module>
    run_action("jupyter-releaser check-python")
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/actions/common.py", line 25, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 91, in run
```

**Comment by jtpio** [comment]
Looks like we could try with the repo workflows directly? https://github.com/jupyter-server/jupyter-resource-usage/actions/workflows/prep-release.yml
