### ISSUE TITLE
Getting 'Unhandled error' when it tries to open control channel

### ISSUE THREAD

**Issue by rucshah** [jupyter-server/jupyter-resource-usage#181]
Hi,
Thanks for this great extension. I tried to configure this in my setup (JupyterServer + JupyterLab + Jupyter Enterprise Gateway) which is running in kubernetes. My setup has
`jupyter_client          8.0.3
jupyter_core            5.2.0
jupyter-resource-usage  0.7.2
jupyter-server          1.23.42
jupyterhub              3.1.1
jupyterlab              3.5.2
jupyter_enterprise_gateway 3.1.0
`
But when extension makes a call, I see following exception in jupyter server:
`    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_resource_usage/api.py", line 115, in get
        control_channel = client.control_channel
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/gateway/managers.py", line 765, in control_channel
        assert self.channel_socket is not None
    AssertionError
[W 2023-02-24 22:25:02.920 SingleUserNotebookApp handlers:649] wrote error: 'Unhandled error'`

I am missing something here.

**Comment by fm2022aa** [comment]
I encounter the same issue, maybe this extension not work with enterprise gateway?
