### ISSUE TITLE
No update of memory usage

### ISSUE THREAD

**Issue by Kexiii** [jupyter-server/jupyter-resource-usage#220]
## Description
Memory Usage is not working in my environment

## Reproduce
![Screen Shot 2023-11-04 at 10 55 43](https://github.com/jupyter-server/jupyter-resource-usage/assets/17425627/f6f0fd60-2159-4dfc-a3c3-cd7cb0067d52)
The memory usage is not working and won't update when I run code in cell, and I got this error message in jupyter console, I don't know if it's related:
```
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "*/Python/3.8/lib/python/site-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "*/Python/3.8/lib/python/site-packages/ipykernel/kernelbase.py", line 986, in usage_request
    reply_content["kernel_memory"] = sum(
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

## Context
```
jupyter-resource-usage    1.0.1

IPython          : 8.4.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 8.3.0
jupyter_core     : 5.3.1
jupyter_server   : 2.7.0
jupyterlab       : 4.0.4
nbclient         : 0.6.6
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 7.0.6
qtconsole        : 5.3.1
traitlets        : 5.9.0
```

**Comment by z0gSh1u** [comment]
Same issue. It seems some process the kernel tallys memory for is already terminated, causing a None entry in summed items.

**Comment by holzman** [comment]
This should be fixed if you update ipykernel to at least 6.29.1: https://github.com/ipython/ipykernel/pull/1204
