### ISSUE TITLE
The 'mem_limit' trait of a ResourceUseDisplay instance expected an int or a callable, not the str '1111'.

### ISSUE THREAD

**Issue by masip85** [jupyter-server/jupyter-resource-usage#86]
Installing nbreuse for jupyterlab 2.2.9, I get following error at cpu_limit or memlimit when I use like this:

```
docker run --name ${NAME}_cont \
	--cpus=$CONTAINER_CPU_PER --cpuset-cpus=$CONTAINER_CPU_ARRAY \
	--memory=${CONTAINER_MEM} \
	[...]
	$IMAGE_NAME start.sh jupyter lab \
	--NotebookApp.password=$(<../.hashedPass.pwd) \
    --NotebookApp.base_url="/" \
    --NotebookApp.ResourceUseDisplay.mem_limit=${CONTAINER_MEM}   \
    --NotebookApp.ResourceUseDisplay.track_cpu_percent=True \
    --NotebookApp.ResourceUseDisplay.cpu_limit=$CONTAINER_CPU_NUM \
    --NotebookApp.allow_origin='https://colab.research.google.com' \
    --NotebookApp.port_retries=0
    
```
   

> W 23:51:55.317 LabApp] Error loading server extension nbresuse
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1945, in init_server_extensions
>         func(self)
>       File "/opt/conda/lib/python3.8/site-packages/nbresuse/__init__.py", line 35, in load_jupyter_server_extension
>         resuseconfig = ResourceUseDisplay(parent=nbapp)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/config/configurable.py", line 104, in __init__
>         self.config = config
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 604, in __set__
>         self.set(obj, value)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 593, in set
>         obj._notify_trait(self.name, old_value, new_value)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1217, in _notify_trait
>         self.notify_change(Bunch(
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1227, in notify_change
>         return self._notify_observers(change)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
>         c(event)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 888, in compatible_observer
>         return func(self, change)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/config/configurable.py", line 208, in _config_changed
>         self._load_config(change.new, traits=traits, section_names=section_names)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/config/configurable.py", line 175, in _load_config
>         setattr(self, name, deepcopy(config_value))
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 604, in __set__
>         self.set(obj, value)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 578, in set
>         new_value = self._validate(obj, value)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 610, in _validate
>         value = self.validate(obj, value)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1981, in validate
>         self.error(obj, value)
>       File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 690, in error
>         raise TraitError(e)
>     traitlets.traitlets.TraitError: The 'mem_limit' trait of a ResourceUseDisplay instance expected an int or a callable, not the str '14427566899'.

It's always a str, it doesn't matter I use hardcoded number, | bc ,or expr.

**Comment by jtpio** [comment]
Thanks @masip85.

This looks like an issue with traitlets 5, and a change in the way command line parameters are parsed.

It will probably for now by downgrading to traitlets 4. Although this indicates a fix in `jupyter-resource-usage` might also be needed.

**Comment by masip85** [comment]
So requirements of jupyter-resource-usage  must change?
